### ISSUE TITLE
Auto type and range checking

### ISSUE THREAD

**Issue by godrays** [docopt/docopt.cpp#39]
I gave it a try! Very nice work.

I would like to propose one thing to make this work really unbeatable:

**Adding type check and range information section**

This could be in USAGE string buffer or could be given in a separate buffer.

Example:

`static const char USAGE[] =
R"(Naval Fate.

```
Usage:
  naval_fate ship new <name>...
  naval_fate ship <name> move <x> <y> [--speed=<kn>]
  naval_fate ship shoot <x> <y>
  naval_fate set distance <d>
  naval_fate set filename <file>
  naval_fate mine (set|remove) <x> <y> [--moored | --drifting]
  naval_fate (-h | --help)
  naval_fate --version

Restrictions:
    <name> : string ["apple", "grape", "blueberry"] { default: "apple" }
    <file> : string
    <x> : integer {default: 10}
    <y> : integer [-10..-2000] {default: 20}
    <kn> : unsigned integer [10, 20, 30, 40]
    <d> : float

Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in knots [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.
```

)";`

Type and range error messages can be printed automatically for an argument.

This can help to reduce a lot of type-check / value-range error handling lines and can make our code perfectly clean.

Alternatively, restrictions section can be hidden from user and can be given as a second argument to the parser.

```
static const char RESTRICTIONS[] =
R"(
        <name> : string [ "apple", "grape", "blueberry" ] { default: "apple" }
        <file> : string
        <x> : integer { default: 10 }
        <y> : integer [ -10..-2000 ] { default: 20 }
        <kn> : unsigned integer [ 10, 20, 30, 40 ]
        <d> : float
)";

...
    std::map<std::string, docopt::value> args
        = docopt::docopt(USAGE, RESTRICTIONS,
                         { argv + 1, argv + argc },
                         true,               // show help if requested
                         "Naval Fate 2.0");  // version string
...

```

I think restrictions section should be optional. This way, it can be backward compatible. Simple and advanced mode.

Any comments?

**Comment by GamePad64** [comment]
This should be in upstream docopt specification. docopt.cpp strictly follows it and cannot make decisions like these.

**Comment by godrays** [comment]
Can't we add it as an extension feature? Without giving RESTRICTION rules, docopt still follows the same specification we have today.

**Comment by jaredgrubb** [comment]
This seems like an anti-feature. Most man pages for command line tools dont use words like "unsigned integer" or "float", and the usage string is meant to be even more compact than a man page.

I could see the value in some functions to help do better type checking after the fact, but I'm not sure what that would look like or whether it's really in docopt's purview to provide that.

**Comment by schuhschuh** [comment]
The textual CLI description of `docopt` is pretty neat! 

I just think something along the lines as suggested in this issue should be a must for a library that really wants to "parse" the arguments rather than just putting them into a dictionary.

I also think it's not at all an "anti-feature" to specify type and constraints in the specification from which the parser is generated. This specification shouldn't be taken to be identical to the usage/help message presented to the user. To me, what `docopt` can offer is a CLI specification "language" closer to what we are used to as end-users of command-line tools (i.e., usage/help message) instead of a less-readable language such as [Slicer's XML schema](https://www.slicer.org/wiki/Documentation/Nightly/Developers/SlicerExecutionModel#Module_Description) from which [TCLAP](http://tclap.sourceforge.net/) code is generated.

Nobody requires that a type description with constraints be part of the `--help` output. The text string parsed by `docopt` to generate the parser to parse the command-line arguments may contain additional information. In particular type and possibly range specifications are needed, however, to provide the functionality of actually parsing the argument strings and convert them to their actual type. Something mandatory for type-safe languages such as C++. Having users do all the parsing which includes generating a nice  error messages when the argument is of incorrect type ("3.1" for an integer type), limits applications for which this library is useful (i.e., those with mainly string arguments as is the case in many of the included examples).

Just my two cents, though :-).

**Comment by schuhschuh** [comment]
PS: Maybe I am partially incorrect in believing docopt doesn't parse argument strings given the docopt::docvalue type. Just cannot see in the README how it knows what type to convert to... (also the example in the README contains "15" rather than the number 15 in the dictionary for --speed). I see that a string is on-demand converted by docopt::value::asLong.

**Comment by jaredgrubb** [comment]
This project is a port of the original 'docopt' and I really dont want to add extended syntax beyond what they support. 

In the README, the reason that it's "15" and not 15 is because the syntax does not support type information because in general it's not there. For example "--style=short" and "--style=15" are both allowed, and "--version=15" could be a number but "--version=15.1.1" is definitely not a number. We added "asLong" convenience to make the simple thing easy, but if you need much past that, I'm not sure how to express that in the docopt syntax.

I am open to documentation patches to try to make the library more useful, but I am not comfortable accepting syntax extensions beyond what docopt supports.
