### ISSUE TITLE
I just tried docopt.cpp

### ISSUE THREAD

**Issue by tobimensch** [docopt/docopt.cpp#5]
Hi,

thanks for making this.

Just tried it...! Yay

Here are a view observations:

1) There's no buildsystem coming with docopt.cpp . Maybe you intended that. Anyhow, it would be good if you had some crossplatform way to generate a lib and maybe distributions can include it?!

2)

```
    map<string, docopt::value> args = docopt::docopt(USAGE, 
                                                  { argv + 1, argv + argc },
                                                  true,               // show help if requested
                                                  "prog 0.0.0.1");  // version string

    if ( args["--foobar"].asBool() == true )
    {
        foobar = 2;
    }
```

Coming from python having to manually convert that with asBool() is really looking ugly. Ok, coming from python many things look ugly of tedious in C++.
But I think you could create a docopt::map type (i.e. derived from std::map) that would work better and could overwrite that index (pretty sure it's possible in C++)  to automatically return the correct type.
If that's not possible, alternative Idea would be to extend the value type to have some basic value checking:

UPDATE:
Ok, I looked at the code now. You did overload the == operator.... but when I tried == true, there were compiler issues. So, maybe there's just a bug and nothing else there.

**Comment by jaredgrubb** [comment]
This now has CMake support so I think this issue is moot now. I'm going to close this but if you think there's still something to track, comment and we can reopen it.

**Comment by lightness1024** [comment]
@tobimensch 

> Use objects that can implicitly be converted into "the right one" 

That's what variant is. In an expression with an operator, that operator (say ==) will have "variant, bool" passed to it, so the variant overload will be called since it must be a template in fact. "variant, T" the compiler instanciates it with "variant, T=bool". Then the operator implementation can verify at compile time that bool is one of the types that this variant can contain, and accept the build.
Then at runtime, like in python, the dynamic type checking is deferred at the last moment, according to what resides in the variant.
Variant (or discriminated enums) are `any` with a strictly limited number of acceptable types.
python is a language where all variable, is an `any`.
C++ therefore, contains python :) awsome no ?
